name: Prune NPM tags
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  prune:
    name: Prune NPM tags
    runs-on: ubuntu-latest
    steps:
      - run: npm view --json | jq -r '.["dist-tags"] | to_entries | .[] | select(.key != "latest") | select(.key != "next") | .key' | xargs -I % npm dist-tag rm viem %